export type Issue = {
  title: string;
  detail: string;
  impact: "high" | "medium" | "low";
};

export type Section = {
  score: number;
  summary: string;
  strengths: string[];
  issues: Issue[];
};

export type CriticReport = {
  url: string;
  siteTitle: string;
  verdict: string;
  overallScore: number;
  thinContent: boolean;
  ui: Section;
  copy: Section;
  conversion: Section;
};

export type StoredReport = {
  id: string;
  createdAt: string;
  report: CriticReport;
};

const emptySection = (): Section => ({
  score: 0,
  summary: "",
  strengths: [],
  issues: [],
});

function asString(value: unknown, fallback = ""): string {
  return typeof value === "string" ? value : fallback;
}

function asScore(value: unknown): number {
  const n = typeof value === "number" ? value : Number(value);
  if (!Number.isFinite(n)) return 0;
  return Math.max(0, Math.min(100, Math.round(n)));
}

function asStringList(value: unknown): string[] {
  if (!Array.isArray(value)) return [];
  return value.map((item) => asString(item)).filter(Boolean).slice(0, 8);
}

function asIssues(value: unknown): Issue[] {
  if (!Array.isArray(value)) return [];
  return value
    .map((raw) => {
      const item = (raw ?? {}) as Record<string, unknown>;
      const impact = asString(item['impact']).toLowerCase();
      return {
        title: asString(item['title']),
        detail: asString(item['detail']),
        impact: (impact === "high" || impact === "low" ? impact : "medium") as Issue["impact"],
      };
    })
    .filter((item) => item.title || item.detail)
    .slice(0, 8);
}

function asSection(value: unknown): Section {
  if (!value || typeof value !== "object") return emptySection();
  const raw = value as Record<string, unknown>;
  return {
    score: asScore(raw['score']),
    summary: asString(raw['summary']),
    strengths: asStringList(raw['strengths']),
    issues: asIssues(raw['issues']),
  };
}

/** Normalizes untrusted model output into a safe, renderable report. */
export function normalizeReport(
  raw: unknown,
  fallback: { url: string; siteTitle: string; thinContent: boolean },
): CriticReport {
  const data = (raw && typeof raw === "object" ? raw : {}) as Record<string, unknown>;
  const ui = asSection(data['ui']);
  const copy = asSection(data['copy']);
  const conversion = asSection(data['conversion']);
  const sectionScores = [ui.score, copy.score, conversion.score].filter((s) => s > 0);
  const derived = sectionScores.length
    ? Math.round(sectionScores.reduce((a, b) => a + b, 0) / sectionScores.length)
    : 0;
  const overall = asScore(data['overallScore']) || derived;

  return {
    url: fallback.url,
    siteTitle: asString(data['siteTitle'], fallback.siteTitle) || fallback.siteTitle,
    verdict: asString(data['verdict'], "Analysis complete."),
    overallScore: overall,
    thinContent: fallback.thinContent,
    ui,
    copy,
    conversion,
  };
}

export const SECTION_META = [
  { key: "ui", label: "UI / UX", blurb: "Layout, hierarchy, spacing, color" },
  { key: "copy", label: "Copywriting", blurb: "Headline clarity, CTA strength, messaging" },
  { key: "conversion", label: "Conversion", blurb: "How to lift signups and sales" },
] as const;

export function reportToMarkdown(report: CriticReport): string {
  const lines: string[] = [];
  lines.push(`# Landing Page Critique — ${report.siteTitle || report.url}`);
  lines.push(`URL: ${report.url}`);
  lines.push(`Overall score: ${report.overallScore}/100`);
  lines.push("");
  lines.push(report.verdict);
  for (const meta of SECTION_META) {
    const section = report[meta.key];
    lines.push("");
    lines.push(`## ${meta.label} — ${section.score}/100`);
    if (section.summary) lines.push(section.summary);
    if (section.strengths.length) {
      lines.push("");
      lines.push("**What works**");
      for (const item of section.strengths) lines.push(`- ${item}`);
    }
    if (section.issues.length) {
      lines.push("");
      lines.push("**What to fix**");
      for (const issue of section.issues) {
        lines.push(`- [${issue.impact.toUpperCase()}] ${issue.title} — ${issue.detail}`);
      }
    }
  }
  lines.push("");
  lines.push("Generated by Landing Page Critic");
  return lines.join("\n");
}
