import { SECTION_META, type CriticReport } from "./critic-types";

/** Renders the report as a paginated PDF in the browser and triggers a download. */
export async function downloadReportPdf(report: CriticReport) {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 48;
  const maxWidth = pageWidth - margin * 2;
  let y = margin;

  const ensureSpace = (needed: number) => {
    if (y + needed > pageHeight - margin) {
      doc.addPage();
      y = margin;
    }
  };

  const write = (
    text: string,
    options: { size?: number; style?: "normal" | "bold"; gap?: number; color?: [number, number, number] } = {},
  ) => {
    const { size = 11, style = "normal", gap = 8, color = [30, 30, 35] } = options;
    doc.setFont("helvetica", style);
    doc.setFontSize(size);
    doc.setTextColor(color[0], color[1], color[2]);
    const lines = doc.splitTextToSize(text, maxWidth) as string[];
    ensureSpace(lines.length * (size + 3));
    doc.text(lines, margin, y);
    y += lines.length * (size + 3) + gap;
  };

  write("Landing Page Critique", { size: 20, style: "bold", gap: 4 });
  write(report.siteTitle || report.url, { size: 12, style: "bold", gap: 2 });
  write(report.url, { size: 10, color: [110, 110, 120], gap: 14 });
  write(`Overall score: ${report.overallScore}/100`, { size: 14, style: "bold", gap: 6 });
  write(report.verdict, { size: 11, gap: 18 });

  for (const meta of SECTION_META) {
    const section = report[meta.key];
    ensureSpace(60);
    write(`${meta.label} — ${section.score}/100`, { size: 14, style: "bold", gap: 4 });
    if (section.summary) write(section.summary, { size: 11, gap: 10 });
    if (section.strengths.length) {
      write("What works", { size: 11, style: "bold", gap: 4 });
      for (const item of section.strengths) write(`•  ${item}`, { size: 10, gap: 4 });
      y += 6;
    }
    if (section.issues.length) {
      write("What to fix", { size: 11, style: "bold", gap: 4 });
      for (const issue of section.issues) {
        write(`•  [${issue.impact.toUpperCase()}] ${issue.title}`, { size: 10, style: "bold", gap: 2 });
        write(`    ${issue.detail}`, { size: 10, gap: 6, color: [70, 70, 80] });
      }
    }
    y += 10;
  }

  ensureSpace(40);
  write("Generated by Landing Page Critic", { size: 9, color: [140, 140, 150] });

  const host = report.url.replace(/^https?:\/\//, "").replace(/[^a-z0-9.-]/gi, "-");
  doc.save(`landing-page-critique-${host}.pdf`);
}
